# Generated by Django 3.2 on 2021-07-14 18:46

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import django_runtime_tags.pickled_object_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuntimeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Use {{ Key }} in the template', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[\\dA-Za-z]+[\\dA-Za-z_.]*$', 'Not a valid tag name')])),
                ('value', django_runtime_tags.pickled_object_field.PickledObjectField(editable=False, help_text='Use True, False, arbitrary Text, or any serializable Python value!', null=True)),
                ('valid_start', models.DateTimeField(default=django.utils.timezone.now, help_text='Make template variable available starting at this date/time')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Runtime Tag',
            },
        ),
    ]
