# Generated by Django 3.2 on 2021-07-15 07:51

from django.db import migrations

tag_data = [
    {
        'pk': 1,
        'value': False,
        'key': 'EnableEventSubmission'
    },
    {
        'pk': 2,
        'value': 'Add Your Event',
        'key': 'EventSubmissionEnabledText'
    },
    {
        'pk': 3,
        'value': 'Online event submissions are now closed, however you may submit events at Playa Info inside Black Rock City.',
        'key': 'EventSubmissionDisabledText'
    },
    {
        'pk': 5,
        'value': False,
        'key': 'BrowseThisYearEvents'
    },
    {
        'pk': 6,
        'value': 1550,
        'key': 'EventLimit'
    },
    {
        'pk': 7,
        'value': 'The submission limit',
        'key': 'EventLimitReachedText'
    },
    {
        'pk': 8,
        'value': False,
        'key': 'AllowLocationInfo'
    },
    {
        'pk': 12,
        'value': 'SUBMIT YOUR VIRTUAL EVENT',
        'key': 'VirtualEventSubmissionEnabledText'
    },
    {
        'pk': 13,
        'value': 'BROWSE VIRTUAL EVENTS',
        'key': 'VirtualEventBrowseEnabledText'
    },
    {
        'pk': 14,
        'value': False,
        'key': 'VirtualBrowseThisYearEvents'
    },
    {
        'pk': 15,
        'value': False,
        'key': 'VirtualEnableEventSubmission'
    },
    {
        'pk': 16,
        'value': 'Event submission is closed.',
        'key': 'VirtualEventSubmissionDisabledText'
    }
]

def add_runtime_tags(apps, schema_editor):
    """ Add default BMP runtime tags.
    """

    RuntimeTag = (apps.get_model('django_runtime_tags', 'RuntimeTag'))

    for t in tag_data:
        tag, created = RuntimeTag.objects.update_or_create(pk=t.pop('pk'), defaults=t)


class Migration(migrations.Migration):

    dependencies = [
        ('django_runtime_tags', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_runtime_tags)
    ]
